module async_fifo #(
    parameter DATA_WIDTH = 8,
    parameter ADDR_WIDTH = 4
)(
    // Write Domain Interface 
    input  wire                  wr_clk,
    input  wire                  wr_rst_n,
    input  wire                  wr_en,
    input  wire [DATA_WIDTH-1:0] din,
    output wire                  full,
    
    // Read Domain Interface 
    input  wire                  rd_clk,
    input  wire                  rd_rst_n,
    input  wire                  rd_en,
    output wire [DATA_WIDTH-1:0] dout,
    output wire                  empty
);

    
    localparam FIFO_DEPTH = (1 << ADDR_WIDTH);

   
    // Binary memory addresses from pointer blocks to the dual-port RAM
    wire [ADDR_WIDTH-1:0] waddr;
    wire [ADDR_WIDTH-1:0] raddr;
    
    // Local Gray-code pointers generated by the respective clock domains
    wire [ADDR_WIDTH:0]   wptr;
    wire [ADDR_WIDTH:0]   rptr;
    
    // Cross-domain synchronized Gray-code pointers coming out of the CDC bridges
    wire [ADDR_WIDTH:0]   wq2_rptr; // Read pointer synchronized to wr_clk domain
    wire [ADDR_WIDTH:0]   rq2_wptr; // Write pointer synchronized to rd_clk domain
    
    // Gated internal write enable: only allow memory writes if user wants to write AND FIFO is not full
    wire                  mem_wr_en;
    assign mem_wr_en = wr_en && ~full;


    // 1. Dual-Port Storage Core
    fifo_mem #(
        .DATA_WIDTH (DATA_WIDTH),
        .ADDR_WIDTH (ADDR_WIDTH),
        .FIFO_DEPTH (FIFO_DEPTH)
    ) u_fifo_mem (
        .wr_clk     (wr_clk),
        .wr_en      (mem_wr_en),
        .waddr      (waddr),
        .din        (din),
        .raddr      (raddr),
        .dout       (dout)
    );

    // 2. Write Pointer & Full Flag Control Logic
    fifo_wptr #(
        .addr_width (ADDR_WIDTH)
    ) u_fifo_wptr (
        .wr_clk     (wr_clk),
        .wr_rst_n   (wr_rst_n),
        .wr_en      (wr_en),
        .wq2_rptr   (wq2_rptr), // Synchronized read pointer input
        .full       (full),
        .waddr      (waddr),
        .wptr       (wptr)       // Local Gray pointer output
    );

    // 3. Read Pointer & Empty Flag Control Logic
    fifo_rptr #(
        .addr_width (ADDR_WIDTH)
    ) u_fifo_rptr (
        .rd_clk     (rd_clk),
        .rd_rst_n   (rd_rst_n),
        .rd_en      (rd_en),
        .rq2_wptr   (rq2_wptr), // Synchronized write pointer input
        .empty      (empty),
        .raddr      (raddr),
        .rptr       (rptr)       // Local Gray pointer output
    );

    // 4. CDC Synchronizer: Passing Read Pointer into Write Clock Domain
   cdc_sync #(
    .addr_width (ADDR_WIDTH)
) u_sync_r2w (
    .clk        (wr_clk),
    .rst_n      (wr_rst_n),
    .data_in    (rptr),
    .data_out   (wq2_rptr)
);

    // 5. CDC Synchronizer: Passing Write Pointer into Read Clock Domain
    
cdc_sync #(
    .addr_width (ADDR_WIDTH)
   ) u_sync_w2r (          
    .clk        (rd_clk),   
    .rst_n      (rd_rst_n),     
    .data_in    (wptr),     
    .data_out   (rq2_wptr)  
);

endmodule
